export const TableHeaders = [
  { label: "Company Name", value: "Company Name" },
  { label: "Strike price", value: "Strike price" },
  { label: "Entry", value: "Entry" },
  { label: "Moved", value: "Moved" },
  { label: "No of lots", value: "No of lots" },
  { label: "Shares per lot", value: "Number of shares per lot" },
  { label: "Profit/loss", value: "Profit loss" },
];

export const TableData = [
  {
    "Company Name": "Biocon",
    "Strike price": "850 CE",
    Entry: 9,
    Moved: 18,
    "Profit loss": 22500,
    "No of lots": 1,
    "Number of shares per lot": 2500,
  },
  {
    "Company Name": "Tata chemicals",
    "Strike price": "1030 CE",
    Entry: 38,
    Moved: 36,
    "Profit loss": 1100,
    "No of lots": 1,
    "Number of shares per lot": 500,
  },
  {
    "Company Name": "Shriram Finance",
    "Strike price": "1800 CE",
    Entry: 75,
    Moved: 80,
    "Profit loss": 3000,
    "No of lots": 1,
    "Number of shares per lot": 600,
  },
  {
    "Company Name": "IOC",
    "Strike price": "100CE",
    Entry: 2.25,
    Moved: 2.75,
    "Profit loss": 4875,
    "No of lots": 1,
    "Number of shares per lot": 9750,
  },
  {
    "Company Name": "Coal India",
    "Strike price": "835 CE",
    Entry: 5.55,
    Moved: 5.75,
    "Profit loss": 5250,
    "No of lots": 1,
    "Number of shares per lot": 4200,
  },
  {
    "Company Name": "Granules",
    "Strike price": "300 CE",
    Entry: 17.25,
    Moved: 18.5,
    "Profit loss": 2500,
    "No of lots": 1,
    "Number of shares per lot": 2000,
  },
  {
    "Company Name": "Tata Motors",
    "Strike price": "630 CE",
    Entry: 21,
    Moved: 22.5,
    "Profit loss": 2100,
    "No of lots": 1,
    "Number of shares per lot": 1425,
  },
  {
    "Company Name": "Reliance",
    "Strike price": "2700 CE",
    Entry: 58,
    Moved: 70,
    "Profit loss": 3000,
    "No of lots": 1,
    "Number of shares per lot": 260,
  },
  {
    "Company Name": "Ashok Leyland",
    "Strike price": "170 CE",
    Entry: 5.2,
    Moved: 7,
    "Profit loss": 9000,
    "No of lots": 1,
    "Number of shares per lot": 5000,
  },
  {
    "Company Name": "Siemens",
    "Strike price": "350 CE",
    Entry: 140,
    Moved: 150,
    "Profit loss": 2750,
    "No of lots": 1,
    "Number of shares per lot": 275,
  },
  {
    "Company Name": "Hindalco",
    "Strike price": "435 CE",
    Entry: 10.8,
    Moved: 12,
    "Profit loss": 1650,
    "No of lots": 1,
    "Number of shares per lot": 1400,
  },
  {
    "Company Name": "HDFC Life",
    "Strike price": "690 CE",
    Entry: 16.4,
    Moved: 18,
    "Profit loss": 1750,
    "No of lots": 1,
    "Number of shares per lot": 400,
  },
  {
    "Company Name": "Dixon",
    "Strike price": "4400 CE",
    Entry: 150,
    Moved: 120,
    "Profit loss": 6000,
    "No of lots": 1,
    "Number of shares per lot": 1100,
  },
  {
    "Company Name": "National Aluminium",
    "Strike price": "86 CE",
    Entry: 3.4,
    Moved: 3.2,
    "Profit loss": 1500,
    "No of lots": 1,
    "Number of shares per lot": 200,
  },
  {
    "Company Name": "Infosys",
    "Strike price": "1400 CE",
    Entry: 32,
    Moved: 45,
    "Profit loss": 5200,
    "No of lots": 1,
    "Number of shares per lot": 7500,
  },
  {
    "Company Name": "Polycab",
    "Strike price": "4200 CE",
    Entry: 130,
    Moved: 155,
    "Profit loss": 4500,
    "No of lots": 1,
    "Number of shares per lot": 400,
  },
  {
    "Company Name": "DLF",
    "Strike price": "500 CE",
    Entry: 16.3,
    Moved: 18,
    "Profit loss": 2800,
    "No of lots": 1,
    "Number of shares per lot": 300,
  },
  {
    "Company Name": "Hindpetro",
    "Strike price": "300 CE",
    Entry: 7.4,
    Moved: 5.4,
    "Profit loss": 2700,
    "No of lots": 1,
    "Number of shares per lot": 1650,
  },
  {
    "Company Name": "Shriram Finance",
    "Strike price": "1800 CE",
    Entry: 47.5,
    Moved: 60,
    "Profit loss": 7500,
    "No of lots": 1,
    "Number of shares per lot": 2700,
  },
  {
    "Company Name": "ACC",
    "Strike price": "1840 CE",
    Entry: 94,
    Moved: 110,
    "Profit loss": 4800,
    "No of lots": 1,
    "Number of shares per lot": 600,
  },
  {
    "Company Name": "L&T",
    "Strike price": "2600 CE",
    Entry: 100,
    Moved: 103,
    "Profit loss": 1050,
    "No of lots": 1,
    "Number of shares per lot": 300,
  },
  {
    "Company Name": "Torrent Pharma",
    "Strike price": "200 CE",
    Entry: 80,
    Moved: 70,
    "Profit loss": 5000,
    "No of lots": 1,
    "Number of shares per lot": 300,
  },
  {
    "Company Name": "IB",
    "Strike price": "135 CE",
    Entry: 7,
    Moved: 10,
    "Profit loss": 15300,
    "No of lots": 1,
    "Number of shares per lot": 500,
  },
];
